apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhsummit23-poi-gateway-app-dev
  annotations:
    argocd/app-name: rhsummit23-poi-gateway-app-dev
    backstage.io/kubernetes-id: rhsummit23-poi-gateway-app-dev
    backstage.io/kubernetes-namespace: rhsummit23
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=rhsummit23-poi-gateway-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23JanusN/rhsummit23-gateway
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/rhsummit23/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.summit23bis.17gd.p1.openshiftapps.com/k8s/ns/rhsummit23/deployments/poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.summit23bis.17gd.p1.openshiftapps.com/#https://github.com/Summit23JanusN/rhsummit23-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:rhsummit23"
  system: workshop-system-rhsummit23
  providesApis:
    - gateway-api-rhsummit23
  consumesApis:
    - backend-api-rhsummit23
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-rhsummit23
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:rhsummit23"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-rhsummit23
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://poi-gateway-app-rhsummit23.summit23bis.17gd.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23JanusN/rhsummit23-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:rhsummit23"
  system: workshop-system-rhsummit23
  definition:
    $text: https://github.com/Summit23JanusN/rhsummit23-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
